### PR TITLE
apex plugin changes:

### PR DESCRIPTION
**Pull request by wouter-rombouts**
- Width: automatic dropdown width.
- Minimum width for placeholder of multiselect
- Fixed width select2's (e.g. 200px) no longer cuts off the content when the item's text is longer than the        width("..." is used to cut off the text).
- New attribute: text wrapping allows for wrapping on words and whitespace.
- Languages: select2 has default localised strings which are based on the BROWSER_LANGUAGE substitution string.

### CODE REVIEW

**Comment by rimblas** [comment]
I think the localization of Select2 should also depend (or only depend) on the APEX Session `APEX_UTIL.GET_SESSION_LANG` because an APEX application could function in a language different from that of the browser.

**Comment by nbuytaert1** [comment]
> I think the localization of Select2 should also depend (or only depend) on the APEX Session APEX_UTIL.GET_SESSION_LANG because an APEX application could function in a language different from that of the browser.

That makes sense, Jorge. Thanks for the input.

Is it possible to map the `APEX_UTIL.GET_SESSION_LANG` to the right language file?

**Comment by rimblas** [comment]
Good question, I don't know.  
In my limited experience, it seems that `APEX_UTIL.GET_SESSION_LANG` match browser lang values.

**Comment by wouter-rombouts** [comment]
Im sorry for the confusion, BROWSER_LANGUAGE is actually the session language. This is not equal to the browser language( as seen in developer toolbar => session). Furthermore APEX_UTIL.GET_SESSION_LANG seemed to return an empty value (atleast for me) and is not usable?(in apex 5.0)

**Pull request closed without merging**
